# Import the Elasticsearch library
import elasticsearch

#Elasticsearch(['406fe72a0b1e4a979516909b134d4e98'])
from elasticsearch import Elasticsearch

# Password for the 'elastic' user generated by Elasticsearch
ELASTIC_PASSWORD = "aOId1OZ0SEYyJ2HW52XEGRSl"

# Found in the 'Manage Deployment' page
CLOUD_ID = "Elastic_search_R:d2VzdHVzMi5henVyZS5lbGFzdGljLWNsb3VkLmNvbTo0NDMkNDA2ZmU3MmEwYjFlNGE5Nzk1MTY5MDliMTM0ZDRlOTgkNDY2YzdhMTJlYzQ3NDUzNTlmNWYxZmRjYjg5YzBiOWM="

# Create the client instance
client = Elasticsearch(cloud_id=CLOUD_ID,basic_auth=("elastic", ELASTIC_PASSWORD))

def elasticsearch_web(query):
    res = client.search(index='websites', body={
        'query': {
            'multi_match': {
                'query': query,
                'fields': ['content' ]#, 'title' , 'images', 'videos']
            }
        },
        'sort': [
            {'time': 'desc'}
        ]
    })

    # `res` will contain the search results
    return res



def elasticsearch_images(query):
    res = client.search(index='images', body={
        'query': {
            'multi_match': {
                'query': query,
                'fields': ['title' ]#, 'title' , 'images', 'videos']
            }
        }
    })

    # `res` will contain the search results
    return res


def elasticsearch_news(query):
    res = client.search(index='news', body={
        'query': {
            'multi_match': {
                'query': query,
                'fields': ['title','content' ]#, 'title' , 'images', 'videos']
            }
        }
    })

    return res